### ISSUE TITLE
运行失败，缺少circle_id

### ISSUE THREAD

**Issue by Guochengjie** [zhanghua000/enaea.edu.cn#1]
登录完成后，提示：
Traceback (most recent call last):
  File "enaea.edu.cn.py", line 339, in <module>
    process_courses(courses=courses)
  File "enaea.edu.cn.py", line 308, in process_courses
    for detail in status.get_details():
TypeError: get_details() missing 1 required positional argument: 'circle_id'

**Comment by arenekosreal** [comment]
已找到问题，请下载新的文件后再试一下，抱歉。

**Comment by Guochengjie** [comment]
更新后能加载课程了，不过接着就报错：
Traceback (most recent call last):
  File "enaea.edu.cn.py", line 339, in <module>
    process_courses(courses=courses)
  File "enaea.edu.cn.py", line 310, in process_courses
    for video in detail.get_videos():
TypeError: get_videos() missing 2 required positional arguments: 'course_id' and 'circle_id'

感谢。

**Comment by arenekosreal** [comment]
啊这。。。看起来我得找个时间慢慢看一下到底有哪些地方在改动之后没有跟着改了，这个问题找到了，已经再次修复

**Comment by Mathisdifficult** [comment]
Traceback (most recent call last):
  File "enaea.edu.cn.py", line 336, in <module>
    process_courses(courses=courses)
  File "enaea.edu.cn.py", line 319, in process_courses
    post_client(video=video)
  File "enaea.edu.cn.py", line 247, in post_client
    client_id=cookies["client_id"]
KeyError: 'client_id'

**Comment by xiaofeng521** [comment]
KeyError: 'client_id'
